name = "vpm"
version = "0.1.0"
description = "Package manager for Vidar"
author = "Paul Cosma <paul.cosma97@gmail.com>"
license = "MIT"
vidar = "2026.10.2"

[scripts]
build = "vidar build cmd/vpm -bin"
run = "vidar run cmd/vpm --"
test = "vidar test lib/semver && vidar test lib/toml"

[dependencies]
